// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: auth/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      *string                `protobuf:"bytes,1,req,name=deviceId" json:"deviceId,omitempty"`
	TokenType     *string                `protobuf:"bytes,2,req,name=tokenType" json:"tokenType,omitempty"`
	AccessToken   *string                `protobuf:"bytes,3,req,name=accessToken" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthInput) Reset() {
	*x = GetAuthInput{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthInput) ProtoMessage() {}

func (x *GetAuthInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthInput.ProtoReflect.Descriptor instead.
func (*GetAuthInput) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthInput) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *GetAuthInput) GetTokenType() string {
	if x != nil && x.TokenType != nil {
		return *x.TokenType
	}
	return ""
}

func (x *GetAuthInput) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

type GetAuthOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthOutput) Reset() {
	*x = GetAuthOutput{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthOutput) ProtoMessage() {}

func (x *GetAuthOutput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthOutput.ProtoReflect.Descriptor instead.
func (*GetAuthOutput) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthOutput) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\"j\n" +
	"\fGetAuthInput\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x02(\tR\bdeviceId\x12\x1c\n" +
	"\ttokenType\x18\x02 \x02(\tR\ttokenType\x12 \n" +
	"\vaccessToken\x18\x03 \x02(\tR\vaccessToken\"'\n" +
	"\rGetAuthOutput\x12\x16\n" +
	"\x06userId\x18\x01 \x02(\x03R\x06userId22\n" +
	"\x04Auth\x12*\n" +
	"\aGetAuth\x12\r.GetAuthInput\x1a\x0e.GetAuthOutput\"\x00B,Z*github.com/NavaRose/lechuoi-protos/auth/pb"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_auth_proto_goTypes = []any{
	(*GetAuthInput)(nil),  // 0: GetAuthInput
	(*GetAuthOutput)(nil), // 1: GetAuthOutput
}
var file_auth_auth_proto_depIdxs = []int32{
	0, // 0: Auth.GetAuth:input_type -> GetAuthInput
	1, // 1: Auth.GetAuth:output_type -> GetAuthOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
